# Generated by Django 5.2.15 on 2026-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revealrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_partner", "Waiting for partner"),
                    ("awaiting_woman", "Waiting for woman to reconfirm"),
                    ("window_open", "Photo review window open"),
                    ("rejected", "Rejected by partner"),
                    ("cancelled", "Cancelled during photo window"),
                    ("revealed", "Revealed"),
                ],
                default="pending_partner",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["man", "status"], name="connect_con_man_id_46c0e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["woman", "status"], name="connect_con_woman_i_0d342a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connectionrequest",
            index=models.Index(
                fields=["requester", "status"], name="connect_con_request_2d2350_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "code"], name="connect_ema_email_9fb5d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["connection", "created_at"],
                name="connect_mes_connect_2925ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["connection", "id"], name="connect_mes_connect_e6466b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revealrequest",
            index=models.Index(
                fields=["connection", "status"], name="connect_rev_connect_c98fe3_idx"
            ),
        ),
    ]
